services:
  main:
    image: roborregos/home:main-cuda
    container_name: home-main-1
    volumes:
      - ./ws:/workspace/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
    network_mode: host
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    env_file:
      - ./main.env
    command: ["source /workspace/ws/devel/setup.bash && rosrun frida_task_manager receptionist_task_manager.py"]
    # command: bash -c "source /workspace/ws/devel/setup.bash &&
    #          rosdep update && sudo apt update && rosdep install --from-paths src -y --ignore-src &&
    #          rosrun frida_task_manager receptionist_task_manager.py"
    tty: true
